### PR TITLE
Our beta project

### PR DESCRIPTION
**Pull request by kitpao**
We finished our 2nd project, please review it

### CODE REVIEW

**Review by uche-inyama — APPROVED** [review]
### Nice work team :raised_hands: Job well done. 
Implement this change; inside your form tag, replace the h3 tags, with a label tag,    ```All the labels are displayed above the input.```  then go ahead and merge to master :rocket:

Use [ GitHack ]( https://raw.githack.com/ ) to add a live version of your project to your README.md file.

**Comment by kitpao** [comment]
thank you! I think we got it right with this change

**Comment by leonmezu1** [comment]
Added suggested final fixes

**Comment by samgaco** [comment]
### You are good to go guys. It is approved :clap: Merge to the master branch and submit the project completion form :+1:

**Pull request merged**
